const SIGN_UP = 'AUTH/SIGN_UP';
const SIGN_IN = 'AUTH/SIGN_IN';
const SIGN_OUT = 'AUTH/SIGN_OUT';
const AUTH_STATE_CHANGED = 'AUTH/AUTH_STATE_CHANGED';

export default {
    SIGN_UP,
    SIGN_IN,
    SIGN_OUT,
    AUTH_STATE_CHANGED
}